### ISSUE TITLE
()-> unrecognised tokens

### ISSUE THREAD

**Issue by tusharsinghal123** [goxr3plus/Java-Speech-Recognizer-Tutorial--Calculator#3]
![capture](https://cloud.githubusercontent.com/assets/25883460/23104105/80816986-f6ed-11e6-8e43-487da734fa9c.PNG)

**Comment by tusharsinghal123** [comment]
Java 1.8 is supported by eclipse luna..working fine with luna

**Comment by goxr3plus** [comment]
👍 You can go higher using more recent Eclipse Version , like Oxygen which
has support for Java 9. Although Luna is pretty good too.
