### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nikhildaw** [goxr3plus/Java-Speech-Recognizer-Tutorial--Calculator#4]
please help
i use windows 10
![screenshot 147](https://cloud.githubusercontent.com/assets/27896289/25306227/8f008f98-27a6-11e7-87e5-777a45ddbf35.png)
![screenshot 148](https://cloud.githubusercontent.com/assets/27896289/25306228/8f3b2cca-27a6-11e7-9dfd-09107df98145.png)
![screenshot 149](https://cloud.githubusercontent.com/assets/27896289/25306229/8f4b382c-27a6-11e7-84f7-9230b2e92fce.png)

help

**Comment by goxr3plus** [comment]
Hello my friend i have made an updated tutorial and refreshed all github packages check it here https://www.youtube.com/watch?v=QfSIZzyZ_jc&feature=youtu.be 

I am sure it will solve your questions :)

**Comment by nikhildaw** [comment]
thank you it worked much love
