### ISSUE TITLE
Eclipse marks Code error

### ISSUE THREAD

**Issue by pabatribick** [goxr3plus/Java-Speech-Recognizer-Tutorial--Calculator#7]
Hello,

I've tried your first Tutorial Step and i can't run the Code because an Semikolon, Komma,... is not correct set. What can i do?

Here a Screenshot:
![bildschirmfoto 2018-01-09 20 58 49](https://user-images.githubusercontent.com/11978788/34740735-bcdbc128-f580-11e7-958e-bf0082f1aa70.png)

**Comment by goxr3plus** [comment]
Investigation must be done. I think a variable may be missing.

**Comment by goxr3plus** [comment]
Investigation must be done. I think a variable may be missing.

**Comment by pabatribick** [comment]
I Copied the Files here from GitHub, so the missing or wrong Variables must be in the File itself.

**Comment by goxr3plus** [comment]
I just checked the file. Go on the x of Eclipse error and read what is says. If it is just a semi color or parentheses it is easy to be fixed.

**Comment by goxr3plus** [comment]
I just checked the file. Go on the x of Eclipse error and read what is says. If it is just a semi color or parentheses it is easy to be fixed.

**Comment by pabatribick** [comment]
The Problem is, i cant this Java-Script without Errors. See what Eclipse mark as an Error:
![eclipse_screen](https://user-images.githubusercontent.com/11978788/34907662-40d80758-f882-11e7-9650-3832f86764db.png)

**Comment by goxr3plus** [comment]
I have posted new tutorials on youtube :). Have you fixed the problems?

**Comment by pabatribick** [comment]
Hey, nice to read that! No sorry, its still the same problem :(

**Comment by goxr3plus** [comment]
Check the nee tutorial i made on Netbeans it may help you solve the
problem.

**Comment by pabatribick** [comment]
Hmm I have tried your new Video, but it has now an other error. He can't find files:
![javabuild](https://user-images.githubusercontent.com/11978788/38489192-eb5c0282-3be5-11e8-9fcf-c3978a8055ae.png)

**Comment by goxr3plus** [comment]
Check this repository, i updated it and it's new :) https://github.com/goxr3plus/sphinx-5-Maven-Example

**Comment by pabatribick** [comment]
Hey, I've tried your new Tutorial. The App is now Running without IDE Errors and i can build it. Now the Problem is, it can't detect any Microphone that I connect (USB or Analog). How can I fix that?

**Comment by goxr3plus** [comment]
Hm yes that's something I haven't tried yet. I will find out very soon and return reply :)

**Comment by goxr3plus** [comment]
@pabatribick  Okay tell me which of tutorial you are trying to compile ? There are many folders in this repository with different tutorials each one :)

**Comment by pabatribick** [comment]
I've tried the German Tutorial. I'm really sad why this isn't work here.... Now i have an new PC and this Tutorial didn't work too. What is happening? Eclipse writes me it has now over 40 errors.... You can not Upload your complete Project to Github? Its much easier for all the users.

**Comment by goxr3plus** [comment]
Hello my friend.... i will tell you what the problem is... the correct way
is to make it a huge Maven project with modules but not all dependencies
are in Maven Central or anywhere else so you see that mess on the
repository. There are 2 folders which contain all the dependencies you
need... appart from that you pick which tutorial you like German Tutorial
has a folder with similar name. You followed the tutorial on youtube and
still problems?


You imported the libraries in project class path?

**Comment by pabatribick** [comment]
More than a Month is past. A new Version of Eclipse was released and I've installed it.

Now I got another Error:

`Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for /home/patrick/eclipse-workspace/SpeechRecognizer/resources/libraries/sphinx4-core-5prealpha-20160628.232526-10.jar
Caused by: java.lang.IllegalArgumentException: sphinx4.core.5prealpha: Invalid module name: '5prealpha' is not a Java identifier`

Hmmm... all Libraries were included exactly like in your Video. Would you look at my PC eg. TeamViewer what can be the Bug be?

**Comment by goxr3plus** [comment]
Tell me something which Java Version are you using?

I haven't compiled this library since 2017.

**Comment by pabatribick** [comment]
Hey! Good News! I have got it to run now. Yaaay!  :-)

But now, is it normal, that i got the Error Message "Microphone not detected" for an analog Microphone? Or do I need an USB-Mic?

**Comment by goxr3plus** [comment]
Ouuuuuu I have tested only with UWB Microphone 🎤 but you know that's from
ajava perspective has to do with input lines.

**Comment by goxr3plus** [comment]
*USB  i. meant :) I am so happy it workssssssss

**Comment by pabatribick** [comment]
Thank you! ☺
