### ISSUE TITLE
please house I need help creating a playfair Cipher of 17 x 17

### ISSUE THREAD

**Issue by abubuhammad** [goxr3plus/Java-Speech-Recognizer-Tutorial--Calculator#9]
Encryption Process for 8bit Characters
Step1: Obtain the plaintext PT and ordered by the password PW from the user.
Step2:Convert the password PW into hexadecimal
Step3: Create a 16x16 matrix using the converted password PW after suppressing repeatable byte: This is accomplished by filling the matrix in a row-wise manner from top to bottom until the password PW is exhausted then continuing with the remaining alphabets of the extended ASCII in ascending order and shuffle the entire matrix once. Increase the size of the matrix to 17x17 with the first row and column keys (A-F and 0-9). 
Step4: Divide the plaintext PT into pairs if the length is odd add a null character at the end 
Step5: Convert the pair into their hexadecimal equivalent 
Step6 a: Get the current pair of the plaintext P 
b. swap the high-order nibble of the first character with the low-order nibble of the second character and vice versa 
c. Is there anymore pair? If yes go to (a) else go to (d) 
d. This gives a modified plaintext P1 
Step7 a.  Apply substitution encryption algorithm on the current pair of character of the modified plaintext P1
b. Shift the character of the key row to the left once 
c. are the row keys in their initial position? If yes go to (c) else go to (d)
d. shift the column character key upward once 
e. Is there anymore pair of character? If yes go to (a) else stop this gives a hexadecimal ciphertext
f. Convert the current 2 byte of hexadecimal into its Unicode equivalent
g. Is there anymore 2 byte? If yes go to (e) else stop this gives a ciphertext C

 Decryption Process 8bit Characters
Decryption process is carried out by following the steps below: 
Step1: Obtain the password PW and ciphertext C from the user 
Step2:Convert the password PW into hexadecimal
Step3:Create a 16x16 matrix using the converted password PW after suppressing repeatable byte: This is accomplished by filling the matrix in a row-wise manner from top to bottom until the password PW is exhausted then continuing with the remaining alphabets of the extended ASCII in ascending order and shuffle the entire matrix once. Increase the size of the matrix to 17x17 with the first row and column to be the keys(A-F and 09).
Step4a: Get the ciphertext C and convert it into its hexadecimal equivalent. 
Step5. Getthe current pair and locate it in the 17x17 matrix and obtain the row and column key alphabet/number respectively that intercept the pair. 
b. Is there anymore pair? If yes go to (a) else go to (c) 
c. This gives a modified hexadecimal plaintext P1 
Step4 a: Get the current pair of the hexadecimal plaintext P1 
b. Swap the high-order nibble of the first character with the low-order nibble of the second character and vice versa. 
c. Is there anymore pair? If yes go to (a) else go to (d) 
d. This gives a modified hexadecimal plaintext P2
Step5 a: Convert the current pair of the modified hexadecimal plaintext P2 to give a character equivalent.
b. Is there anymore pair? If yes go to (a) else go to (c)
c. Stop this gives back the original plaintext characters.

**Comment by goxr3plus** [comment]
Is this project for Nasa? :)

**Comment by abubuhammad** [comment]
No Sir its a school project I have attached the algorithmic steps, please
help

**Comment by goxr3plus** [comment]
It's so complex i read it 3 times to understand the basics. What leason is that project for ma boi?

**Comment by goxr3plus** [comment]
What this has to so with Speech Recognition? Please refer on StackOverflow

**Comment by abubuhammad** [comment]
No sir it has nothing to do with speech recognition I just wanted your help.

**Comment by goxr3plus** [comment]
@abubuhammad  This is out of scope for this repository my friend :)
